format = """
$directory\
[](fg:#1c3144 bg:#596f62)\
$git_branch\
$git_status\
[](fg:#596f62 bg:#7ea16b)\
$time\
[ ](fg:#7ea16b)\
$character"""

[character]
success_symbol = '[\$](bold green)'

[directory]
style = "fg:#ffffff bg:#1c3144"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#596f62"
format = '[[ $symbol $branch ](fg:#ffffff bg:#596f62)]($style)'

[git_status]
style = "bg:#596f62"
modified = "*"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#596f62)]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:#7ea16b"
format = '[[ $time ](fg:#ffffff bg:#7ea16b)]($style)'
